# Generated by Django 4.2.21 on 2025-05-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
